name: Auto Stream Downloader and Publisher

on:
  repository_dispatch:
    types: [run-workflow]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python Dependencies
        run: |
          pip install yt-dlp google-api-python-client google-auth-oauthlib google-auth-httplib2

      - name: Run Downloader and Publisher
        env:
          YOUTUBE_CREDENTIALS: ${{ secrets.YOUTUBE_CREDENTIALS }}
        run: |
          python process.py \
            "${{ github.event.client_payload.video_url }}" \
            "${{ github.event.client_payload.video_title }}" \
            "${{ github.event.client_payload.video_description }}"

